- name: Config KVM hypervisor
  hosts: all
  tasks:
    - name: install hypervisor
      yum: pkg={{item}} state=installed
      with_items:
        - kvm 
        - libvirt 
        - qemu-system-x86
        - qemu-kvm 
        - bridge-utils 
        - virt-install 

    - name: copy add_br0.sh
      copy: src=../scripts/add_br0.sh dest=/root/ha/add_br0.sh

    - name: add br0
      shell: >
        sh /root/ha/add_br0.sh;
        systemctl restart network
