- name: Config pacemaker
  hosts: all
  tasks:
    - name: install pacemaker
      yum: pkg={{item}} state=installed
      with_items:
        - pacemaker 
        - corosync 
        - pcs 
        - resource-agents

    - name: create cluster
      shell: >
        pcs cluster setup --local --name mycluster 192.168.206.151 192.168.206.152;
        pcs cluster start;
        pcs cluster stop
