- name: Config nfs client
  hosts: all
  tasks:
    - name: install nfsclient
      yum: pkg={{item}} state=installed
      with_items:
        - rpcbind
        - nfs-utils

    - name: restart rpcbind
      service: name=rpcbind state=restarted

    - name: mount nfs volume
      shell: >
        mkdir /data;
        echo "192.168.206.150:/mnt/vg01/lv01/share01    /data   nfs     defaults        0 0" >> /etc/fstab;
        mount -a;
        chmod a+rxw /data
